# Generated by Django 2.2.4 on 2019-08-23 21:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancypage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypage',
            name='content',
            field=wagtail.core.fields.StreamField([('text_block', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(max_length=200)), ('content', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancypage',
            name='hero_image',
            field=models.ForeignKey(help_text='test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
