# Generated by Django 2.2.4 on 2019-08-27 16:04

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_auto_20190827_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypage',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancypage',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancypage',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancypage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(max_length=200)), ('content', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'link', 'ol', 'ul', 'embed'])), ('large_text', wagtail.core.blocks.BooleanBlock())])), ('key_stats', wagtail.core.blocks.StructBlock([('stats', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())])))])), ('case_studies', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(max_length=200)), ('case_studies', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.CharBlock()), ('slugline', wagtail.core.blocks.CharBlock()), ('kicker', wagtail.core.blocks.CharBlock()), ('destination', wagtail.core.blocks.URLBlock())])))])), ('call_to_action', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(max_length=200)), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('large_text', wagtail.core.blocks.BooleanBlock()), ('button_destination', wagtail.core.blocks.URLBlock()), ('button_label', wagtail.core.blocks.CharBlock(max_length=30))]))], blank=True, null=True),
        ),
    ]
