# Generated by Django 2.2.4 on 2019-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0015_auto_20190912_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancypage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vacancypage',
            name='salary',
        ),
        migrations.AddField(
            model_name='vacancypage',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
