# Generated by Django 2.2.4 on 2019-11-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0012_auto_20190912_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='preview_image',
            field=models.ForeignKey(help_text='This image appears in social media previews, but not on the page itself', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
